project:
  type: book
  output-dir: docs

book:
  title: "AI assistants for Scientific Coding"
  author: "Chris Brown"
  date: "2025-08-30"
  chapters:
    - index.qmd
    - 02-introduction.qmd
    - 03-set-up.qmd
    - 04-llm-from-api.qmd
    - 05-github-copilot.qmd
    - 06-general-prompting-advice.qmd
    - 07-ai-powered-analysis-workflows.qmd
    - 08-advanced-llm-agents.qmd
    - 09-specification-sheets.qmd
    - 10-research-applications-LLMs.qmd
    - 11-writing-documents.qmd
    - 12-cost-security.qmd
    - 13-ethics-copyright.qmd
    - 14-appendix.qmd
    

bibliography: book.bib

format:
  html:
    code-overflow: wrap
    theme: simplex
    css: style.css
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png