project:
  type: book
  output-dir: docs

book:
  title: "AI assistants for Scientific Coding"
  author: "Chris Brown"
  date: "30/08/2025"
  chapters:
    - index.qmd
    - 02-introduction.qmd
    - 03-set-up.qmd
    - 04-llm-prompting-fundamentals.qmd
    - 05-research-applications-LLMs.qmd
    - 06-github-copilot.qmd
    - 07-specification-sheets.qmd
    - 08-advanced-llm-agents.qmd
    - 09-ethics-copyright.qmd
    - 10-cost-security.qmd

bibliography: book.bib

format:
  html:
    theme: simplex
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png